import type { Webinar } from "@/types/webinar";

export const initialWebinars: Webinar[] = [
  {
    id: "1",
    title: "Building Scalable AI Products",
    slug: "building-scalable-ai-products",
    description:
      "Learn how top companies design, ship, and scale AI-powered products from concept to production. This session covers architecture patterns, model selection, and real-world deployment strategies.",
    coverImage:
      "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80",
    speakerName: "Sarah Chen",
    speakerImage:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
    speakerDesignation: "VP of AI, TechCorp",
    webinarDate: "2026-07-15",
    webinarTime: "10:00 AM EST",
    duration: "90 min",
    category: "AI",
    level: "Intermediate",
    price: 0,
    seats: 500,
    seatsRemaining: 127,
    meetingLink: "https://meet.example.com/ai-products",
    registrationLink: "#register",
    agenda: [
      "Introduction to AI product development lifecycle",
      "Choosing the right models and infrastructure",
      "Building reliable AI pipelines at scale",
      "Case study: From MVP to 1M users",
      "Live Q&A with Sarah Chen",
    ],
    requirements: [
      "Basic understanding of software development",
      "Familiarity with cloud platforms (helpful)",
      "No prior AI experience required",
    ],
    benefits: [
      "Certificate of completion",
      "Access to session recording for 30 days",
      "Exclusive AI product checklist PDF",
      "Networking with 500+ professionals",
    ],
    faqs: [
      {
        question: "Is this webinar suitable for beginners?",
        answer:
          "Yes! While we cover intermediate topics, we explain everything from first principles.",
      },
      {
        question: "Will slides be shared?",
        answer: "Yes, all attendees receive slides and resources within 24 hours.",
      },
    ],
    tags: ["AI", "Product", "Scale"],
    isFeatured: true,
    status: "Upcoming",
  },
  {
    id: "2",
    title: "Leadership in the Digital Age",
    slug: "leadership-digital-age",
    description:
      "Discover modern leadership frameworks for managing remote teams, driving innovation, and building high-performance cultures in fast-moving organizations.",
    coverImage:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80",
    speakerName: "Marcus Williams",
    speakerImage:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80",
    speakerDesignation: "CEO, GrowthLabs",
    webinarDate: "2026-07-18",
    webinarTime: "2:00 PM EST",
    duration: "60 min",
    category: "Leadership",
    level: "All Levels",
    price: 29,
    seats: 300,
    seatsRemaining: 45,
    meetingLink: "https://meet.example.com/leadership",
    registrationLink: "#register",
    agenda: [
      "The new leadership playbook",
      "Building trust in distributed teams",
      "Decision-making under uncertainty",
      "Creating psychological safety",
      "Interactive leadership workshop",
    ],
    requirements: [
      "Open to managers and aspiring leaders",
      "No prerequisites required",
    ],
    benefits: [
      "Leadership assessment toolkit",
      "Certificate of completion",
      "1-on-1 office hours access",
      "Community Slack invite",
    ],
    faqs: [
      {
        question: "Can I get a refund?",
        answer: "Full refund available up to 48 hours before the webinar.",
      },
    ],
    tags: ["Leadership", "Management", "Culture"],
    isFeatured: true,
    status: "Upcoming",
  },
  {
    id: "3",
    title: "Growth Marketing Masterclass",
    slug: "growth-marketing-masterclass",
    description:
      "Master the art and science of growth marketing with proven frameworks for acquisition, activation, retention, and revenue optimization.",
    coverImage:
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    speakerName: "Emily Rodriguez",
    speakerImage:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
    speakerDesignation: "CMO, ScaleUp Inc",
    webinarDate: "2026-07-10",
    webinarTime: "11:00 AM EST",
    duration: "75 min",
    category: "Marketing",
    level: "Intermediate",
    price: 0,
    seats: 1000,
    seatsRemaining: 312,
    meetingLink: "https://meet.example.com/growth-marketing",
    registrationLink: "#register",
    agenda: [
      "Growth loops vs. funnels",
      "Channel strategy and experimentation",
      "Metrics that matter",
      "Case studies from top brands",
      "Live growth audit session",
    ],
    requirements: ["Basic marketing knowledge recommended"],
    benefits: [
      "Growth marketing playbook",
      "Template library access",
      "Certificate included",
    ],
    faqs: [],
    tags: ["Marketing", "Growth", "Analytics"],
    isFeatured: true,
    status: "Live",
  },
  {
    id: "4",
    title: "Cloud Architecture Best Practices",
    slug: "cloud-architecture-best-practices",
    description:
      "Deep dive into cloud-native architecture patterns, cost optimization, and security best practices for modern engineering teams.",
    coverImage:
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80",
    speakerName: "David Park",
    speakerImage:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
    speakerDesignation: "Principal Architect, CloudFirst",
    webinarDate: "2026-07-22",
    webinarTime: "9:00 AM EST",
    duration: "120 min",
    category: "Cloud",
    level: "Advanced",
    price: 49,
    seats: 200,
    seatsRemaining: 18,
    meetingLink: "https://meet.example.com/cloud-arch",
    registrationLink: "#register",
    agenda: [
      "Multi-cloud vs. single cloud strategies",
      "Serverless and container orchestration",
      "Security and compliance frameworks",
      "Cost optimization techniques",
      "Architecture review workshop",
    ],
    requirements: [
      "Experience with at least one cloud provider",
      "Understanding of basic networking concepts",
    ],
    benefits: [
      "Architecture reference diagrams",
      "AWS/Azure/GCP comparison guide",
      "Certificate of completion",
    ],
    faqs: [],
    tags: ["Cloud", "DevOps", "Architecture"],
    isFeatured: false,
    status: "Upcoming",
  },
  {
    id: "5",
    title: "Cybersecurity Essentials for Startups",
    slug: "cybersecurity-essentials-startups",
    description:
      "Protect your startup from day one with practical cybersecurity strategies, compliance basics, and incident response planning.",
    coverImage:
      "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80",
    speakerName: "Alex Thompson",
    speakerImage:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
    speakerDesignation: "CISO, SecureStack",
    webinarDate: "2026-06-28",
    webinarTime: "3:00 PM EST",
    duration: "60 min",
    category: "Cyber Security",
    level: "Beginner",
    price: 0,
    seats: 400,
    seatsRemaining: 0,
    meetingLink: "https://meet.example.com/cybersec",
    registrationLink: "#register",
    agenda: [
      "Security fundamentals for startups",
      "Common vulnerabilities and fixes",
      "Compliance 101 (SOC2, GDPR)",
      "Building a security culture",
      "Q&A session",
    ],
    requirements: ["No technical background required"],
    benefits: ["Security checklist", "Recording available", "Certificate"],
    faqs: [],
    tags: ["Security", "Startup", "Compliance"],
    isFeatured: false,
    status: "Completed",
  },
  {
    id: "6",
    title: "Full-Stack Development with Next.js",
    slug: "fullstack-nextjs",
    description:
      "Build production-ready full-stack applications with Next.js 15, covering App Router, server actions, authentication, and deployment strategies.",
    coverImage:
      "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&q=80",
    speakerName: "James Liu",
    speakerImage:
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&q=80",
    speakerDesignation: "Staff Engineer, Vercel",
    webinarDate: "2026-07-25",
    webinarTime: "1:00 PM EST",
    duration: "90 min",
    category: "Software",
    level: "Intermediate",
    price: 0,
    seats: 800,
    seatsRemaining: 456,
    meetingLink: "https://meet.example.com/nextjs",
    registrationLink: "#register",
    agenda: [
      "App Router deep dive",
      "Server Components vs Client Components",
      "Data fetching patterns",
      "Authentication and authorization",
      "Live coding session",
    ],
    requirements: [
      "JavaScript/TypeScript fundamentals",
      "Basic React knowledge",
    ],
    benefits: [
      "Starter project repository",
      "Certificate of completion",
      "Office hours access",
    ],
    faqs: [],
    tags: ["Next.js", "React", "Full-Stack"],
    isFeatured: true,
    status: "Upcoming",
  },
];
